name: Create release

on:
  schedule:
    - cron: 0 8 */2 * *

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:

    - name: Generate tag
      run: |
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")"

    - name: Create release
      uses: meeDamian/github-release@1.0
      with:
        token: ${{ secrets.OPENWRT_TOKEN }}
        body: Automatic Build | 自动编译